qywechat:
  qywechatUrl: https://qyapi.weixin.qq.com
  corpid: ww0d42fc0f6e0c3c79
  corpsecert: U8Msrf2tm_4M6ajShqF8jhQ3q3psbUH5zyQzi8nWvCk
  bgurl: https://res-wxec-unipt.lorealchina.com/test/20200722/ba47e4ef-ad7d-4819-9d64-fa345d00ebd7.png
